<h1>Add New Product</h1>
<div class="row">
    <div class="col-md-8">
        <form action="/?action=saveproduct" class="form-horizontal"  method="post">
            <div class="form-group">
                <label class="control-label col-sm-2" for="title">Url:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="url" name="url" placeholder="Enter Url" required="">
                </div>
            </div>
            <div class="form-group"> 
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>    
    </div>
</div>
