<h1>Product List</h1>
<div class="row">
    <div class="col-md-8">
        <?php
        $escapeHtml = 'htmlspecialchars';
        $data = $variables;
                
        foreach ($data as $product)
        {
            $imageurl = '';
            $listUrl = json_decode($product['url_image'], true);
            if(isset($listUrl[0])) $imageurl = $listUrl[0];
        ?>
                <h3>
                    <?php if(!empty($imageurl)) : ?>
                        <img src="<?php echo $escapeHtml($imageurl) ?>" height="30" width="50">
                    <?php endif; ?>
                    <a href="/?action=productview&id=<?= $product['id'] ?>">
                        <?php 
                        echo $escapeHtml($product['name'])." - ".$escapeHtml($product['price']); 
                        ?>
                    </a>    
                </h3>
            <div class="description">
                <?=  substr( strip_tags($product['description']), 0, 300); ?>
            </div>
            <hr>
            <?php
        }
        ?>

    </div>
</div>
